#!/bin/bash

MAKE=/usr/bin/make
basedir=.

if [ $# -ne 1 ] ; then
	echo "Format is "avrmake flag""
	echo "Type flag as -d for debug"
	echo "Type flag as -p for programming"
fi

if [ -s .TYPE ] ; then
	rm -f .TYPE
fi
  
while getopts "dp" opt ; do
	case $opt in
	d)
	 echo "Set to debug mode" >&2
	 echo "debug" >> .TYPE
	 ;;
	p)
	 echo "Set to programming mode" >&2
	 echo "programming" >> .TYPE
	 ;;
	esac
done

${MAKE} -f makefile main > /dev/null
